### ISSUE TITLE
为什么算出来的clip score是大于1的呢？求解答求解答，谢谢~

### ISSUE THREAD

**Issue by Sophia-615** [Taited/clip-score#1]

**Comment by Taited** [comment]
你好呀, 感谢对这个项目的关注. 请问能不能提供一个你用来测试的数据呢? 我可以尝试复现一下你的问题.

**Comment by Sophia-615** [comment]
您好！谢谢您及时的回复，我的问题目前还没有得到解决。我感觉似乎不是测试数据的问题，因为我看到同样有人也是得出了31左右的clip score，如下图所示：
![image](https://github.com/Taited/clip-score/assets/141799141/80401b22-144d-4971-8d05-ad819323c5cb)，
下面是我其中一张测试数据，和对应的prompt
![fire](https://github.com/Taited/clip-score/assets/141799141/04e5da64-ccfd-4ea6-92ca-1312f5d8835c)，
A dynamic and lively flame that dances and flickers, casting a warm, golden glow. The fire's core is a deep, intense orange, with tongues of flame reaching upward in a mesmerizing dance of light and heat.
我想是不是可能是少做了什么操作导致的？

**Comment by Taited** [comment]
你好呀, 我查看了一下你的例子, clip score本质上是在计算feature之间的cosine similarity, 值域范围确实是不大于1的.
要注意这里的实现参考了[OpenAI的CLIP](https://github.com/openai/CLIP), 实际上最后的结果乘了100. 所以最后CLIP Score计算下来范围在 0~100是合理的. 这样的CLIP Score呈现的方式在后面的学术论文中也是广为接受的, 比如OpenAI实现的Diffusion模型(GLIDE)[https://arxiv.org/abs/2112.10741]中, 他们汇报的CLIP Score就是同样数量级的得分.

**Comment by Sophia-615** [comment]
谢谢您的解答！我刚接触这一块不太清楚，所以我只需要在得出的结果上乘上0.01就是我实际计算出的相似度对吗，再次感谢您耐心的回复！

**Comment by Taited** [comment]
是你理解的这样, 如果没有别的问题我就先关闭这个issue啦
