### ISSUE TITLE
How to calculate the clip score of different images corresponding to the same text

### ISSUE THREAD

**Issue by yudongjian** [Taited/clip-score#2]
Hello,
If I have multiple dog images, 
how can I calculate the score for multiple images at once?
Is there any convenient and fast way? 
I don't seem to have seen it. Could you please help me? Thank you

**Comment by Taited** [comment]
Hi,

Thank you for your interest in my project.

Unfortunately, this project does not currently support calculations between a single text and multiple images.

The easiest solution is to duplicate your text files multiple times and name them to correspond with the image file names.

I may consider supporting this feature in a future version.

**Comment by yudongjian** [comment]
Hello, 
thank you for your code and reply. 
I have made the necessary changes. 
Thank you very much
