### ISSUE TITLE
The value of cosine similarity ranges from -1 to 1. How do you normalize it into [0,100]?

### ISSUE THREAD

**Issue by Delicious-Bitter-Melon** [Taited/clip-score#4]
Thanks for your work.

The value of cosine similarity ranges from -1 to 1. How do you normalize it into [0,100]?

**Comment by Taited** [comment]
Hello, and thank you for your interest in this work.

You are correct that cosine similarity typically ranges from -1 to 1. However, in [OpenAI's CLIP implementation](https://github.com/openai/CLIP), the similarity score is scaled by a factor of 100 (this same scaling is also reported in their subsequent text-to-image model, [GLIDE](https://github.com/openai/glide-text2im)). As a result, the actual score range extends from [-100, 100]. Based on my tests with several samples, the cosine similarity derived from CLIP features tends to be positive, which might explain why you are observing a range between [0, 100].
